#!/bin/bash
#
# Kasutajad failist parooliga
# syntax on
if [ $# -ne 1 ]; then
echo "Kasutusjuhend: $0 failinimi"
else
failinimi=$1
if [ -f $failinimi -a -r $failinimi ]; then
echo "Fail on korras"
for rida in $(cat $failinimi)
do
	kasutajanimi=$(echo "$rida" | cut -f1 -d:)
	sh lisa_kasutaja $kasutajanimi
    echo "$rida" | chpasswd #Antud rida võimaldab kasutajale määrata vastava parooli
  done
  else
   echo "Probleem failiga $failinimi"
 fi
#parameetrite lõpp
fi
