#!/bin/bash
#Kasutaja lisamine ilma paroolita
#
clear
#
if [ $# -ne 1 ]; then
  echo "Kasutusjuhend: $0 kasutajanimi"
else
 kasutajanimi=$1
 useradd $kasutajanimi -m -s /bin/bash
if [ $? -eq 0 ]; then
  echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi."
  cat /etc/passwd | grep $kasutajanimi
  ls -la /home/$kasutajanimi
 else
  echo "Probleem kasutaja $kasutajanimi lisamisega!"
  echo "Probleemi kood on $?"
 fi
# skripti õige kasutamise lõpp
fi
